#!/bin/bash
### This file is covered by the GNU General Public License
### version 3 or later.
###
### Copyright (C) 2021-2023, ALT Linux Team

#############################
### Main execuatable file ###
#############################

# Safety first
set -o errexit
set -o noglob
set -o nounset
set -o errtrace

# Executable name
readonly progname="${0##*/}"

# Full path to this script
readonly scriptname="$(realpath -- "$0")"

# Supplimental sources
readonly supplimental="${scriptname%/*}/libexec"

# Bootstrap
. "$supplimental"/defaults.sh
[ ! -s "/etc/$progname"/restore.ini ] ||
	. "/etc/$progname"/restore.ini
. "$supplimental"/privates.sh
. "$supplimental"/common.sh
. "$supplimental"/parser.sh
. "$supplimental"/config.sh

# Catch all unexpected errors
trap 'unexpected_error "$LINENO" "${BASH_SOURCE[0]}"' ERR

# Entry point
nls_locale_setup
parse_cmdline "$@"
check_prerequires

# Check backup and configuration
if [ -n "${use_backup-}" ]; then
	nls_config backup
	check_backup_metadata
	user_config restore.ini
	[ -z "${use_hooks-}" ] ||
		user_config config.sh
	setup_profile

	if [ -n "${profile-}" ]; then
		user_config "${profile-}"/restore.ini
		[ -z "${use_hooks-}" ] ||
			user_config "${profile-}"/config.sh
	fi

	check_config
fi

# Setup logger and UI
. "$supplimental"/logger.sh

# Check the target disk drive
if [ -n "${use_target-}" ]; then
	nls_config target

	. "$supplimental"/trusted.sh
	. "$supplimental"/target.sh

	check_trusted_boot_hw
	protect_boot_devices
	search_target_drive
fi

# Execute the primary action
if [ "${action-}" = validate ]; then
	. "$supplimental"/validate.sh
else
	nls_config restore

	. "$supplimental"/recovery.sh
fi

# Finalize recovery
[ -z "${finalact-}" ] ||
	. "$supplimental"/finalize.sh
exit 0

