#!/bin/bash
### This file is covered by the GNU General Public License
### version 3 or later.
###
### Copyright (C) 2021-2024, ALT Linux Team

###################
### Main script ###
###################

# Safety first
set -o errexit
set -o noglob
set -o nounset
set -o errtrace

# Executable file name
readonly progname="${0##*/}"

# Full path to this script
readonly scriptname="$(realpath -- "$0")"

# Supplemental sources
readonly libdir="${scriptname%/*}/libexec"

# Bootstrapping
. "$libdir"/defaults.sh
[ ! -s "/etc/$progname"/restore.conf ] ||
	. "/etc/$progname"/restore.conf
. "$libdir"/internal.sh
. "$libdir"/common.sh
. "$libdir"/parser.sh
. "$libdir"/config.sh

# Catching all unexpected errors
trap 'unexpected_error "$LINENO" "${BASH_SOURCE[0]}"' ERR

# Entry point
nls_locale_setup
parse_cmdline "$@"
check_prerequires

# Checking the backup and configuration
if [ -n "${use_backup-}" ]; then
	nls_config backup
	check_backup_metadata
	user_config restore.ini
	[ -z "${use_hooks-}" ] ||
		user_config config.sh
	setup_profile

	if [ -n "${profile-}" ]; then
		user_config "${profile-}"/restore.ini
		[ -z "${use_hooks-}" ] ||
			user_config "${profile-}"/config.sh
	fi

	check_config
fi

# Setting up logging and user interface
. "$libdir"/logger.sh

# Checking the target disk drive
if [ -n "${use_target-}" ]; then
	nls_config target

	. "$libdir"/trusted.sh
	. "$libdir"/target.sh

	check_trusted_boothw
	protect_boot_devices
	search_target_device
fi

# Executing the primary action
if [ "${action-}" = validate ]; then
	. "$libdir"/validate.sh
else
	nls_config restore

	. "$libdir"/restore.sh
fi

# Completing the restore
[ -z "${finalact-}" ] ||
	. "$libdir"/finalize.sh
exit 0

