%define _unpackaged_files_terminate_build 1

%define _progconf %_sysconfdir/%name/restore.conf
%define _progdir %_libexecdir/%name

Name: system-restore
Version: 0.2
Release: alt1

Summary: ALT System Restore and Deployment
License: GPL-3
Group: Archiving/Backup

Url: http://www.altlinux.org/Rescue/Recovery
Source: %name-%version.tar
BuildArch: noarch

Packager: Leonid Krivoshein <klark@altlinux.org>

AutoReq: noshell, noshebang

%description
Deployment and recovery solution. Allows to very
quickly and completely automatically install the
system from a pre-prepared rootfs backup.

%prep
%setup

%install
mkdir -pm0755 %buildroot{%_sysconfdir/%name,%_bindir,%_libexecdir,%_logdir}
cp -Rf libexec %buildroot%_progdir
install -pm0755 %name %buildroot%_bindir/%name
install -m0644 restore.conf %buildroot%_progconf.example
sed -i -e 's,^(readonly libdir)=.*$,\1="%_progdir",' %buildroot%_bindir/%name
:> %buildroot%_logdir/%name.log
:> %buildroot%_progconf
cat >libexec/version.sh <<EOF
# Auto-generated by the build system, do not edit directly!
#
SYSREST_VERSION=%version
SYSREST_BUILD_DATE=$(date '+%%Y%%m%%d')

EOF

%files
%dir %_sysconfdir/%name
%config %_progconf.example
%ghost %config(noreplace) %_progconf
%_bindir/%name
%_progdir
%ghost %_logdir/%name.log
%doc examples

%changelog
* Sat Nov 11 2023 Leonid Krivoshein <klark@altlinux.org> 0.2-alt1
- Experimental build for Sisyphus: WiP!

