%define _unpackaged_files_terminate_build 1

Name: system-restore
Version: 0.2
Release: alt1

Summary: ALT System Restore and Deployment
License: GPL-3
Group: Archiving/Backup

Url: http://www.altlinux.org/Rescue/Recovery
Source: %name-%version.tar
BuildArch: noarch

Packager: Leonid Krivoshein <klark@altlinux.org>

AutoReq: noshell, noshebang

%description
Deploy and restore solution for automatic system install
from the prepared rootfs backup images without query user.

%prep
%setup

%install
mkdir -pm755 %buildroot{%_bindir,/usr/libexec,/var/log}
install -pm755 %name %buildroot%_bindir/%name
sed -i -e 's,^(readonly supplimental)=.*,\1="/usr/libexec/%name",' %buildroot%_bindir/%name
cp -Rf libexec %buildroot/usr/libexec/%name
:> %buildroot/var/log/%name.log
cat >%buildroot/usr/libexec/%name/version.sh <<EOF
# Auto-generated by build system, don't edit directly!
#
SYSREST_VERSION=%version
SYSREST_BUILD_DATE=$(date '+%%Y%%m%%d')

EOF

%files
%_bindir/%name
%dir /usr/libexec/%name
/usr/libexec/%name/*
%ghost /var/log/%name.log
%doc examples

%changelog
* Mon Oct 16 2023 Leonid Krivoshein <klark@altlinux.org> 0.2-alt1
- Experimental build for Sisyphus: WiP!

